# Generated by Django 2.2.10 on 2020-07-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review_review_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='averageRating',
            field=models.FloatField(default=0),
        ),
    ]
