# Generated by Django 2.2.10 on 2020-07-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_averagerating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='averageRating',
        ),
    ]
