# Generated by Django 2.2.10 on 2020-07-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
