# Generated by Django 2.2.10 on 2020-07-19 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_item_is_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='chef_key',
            field=models.CharField(default='19-Jul-2020 (22:32:51.687857)', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('O', 'Order Request Accepted'), ('C', 'Cooking'), ('D', 'Deliverd')], default='O', max_length=1),
        ),
        migrations.CreateModel(
            name='OrderedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='core.OrderItem')),
            ],
        ),
    ]
