# Generated by Django 2.2.10 on 2020-07-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_is_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('O', 'Order Request Accepted'), ('C', 'Cooking'), ('D', 'Deliverd')], default='D', max_length=1),
        ),
    ]
