# Generated by Django 2.2.10 on 2020-07-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200719_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='chef_key',
            field=models.CharField(default='20-Jul-2020 (07:42:13.478963)', max_length=100),
        ),
    ]
