# Generated by Django 2.2.10 on 2020-07-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200720_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='chef_key',
            field=models.CharField(default='20-Jul-2020 (13:00:00.486156)', max_length=100),
        ),
    ]
