# Generated by Django 2.2.10 on 2020-07-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200718_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedlist',
            name='orderitems',
        ),
        migrations.AddField(
            model_name='orderedlist',
            name='orderitems',
            field=models.ManyToManyField(to='core.OrderItem'),
        ),
    ]
