# Generated by Django 2.2.10 on 2020-07-18 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200718_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedlist',
            old_name='orderitems',
            new_name='items',
        ),
    ]
