# Generated by Django 2.2.10 on 2020-07-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200718_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='chef_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
